apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: serendibmall-ingress
  namespace: serendibmall
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: api.serendibmall.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: serendibmall-bff
                port:
                  number: 80
