apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: serendibmall

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - bff.yaml
  - product-command.yaml
  - product-query.yaml
  - inventory.yaml
  - order.yaml
  - payment.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: serendibmall
  app.kubernetes.io/managed-by: kustomize
